from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID


class UserRepositoryProtocol(Protocol):
    async def get_by_email(self, email: str) -> Any: ...
    async def get_by_id(self, user_id: UUID) -> Any: ...
    async def create(self, **kwargs: Any) -> Any: ...
    async def update(self, user_id: UUID, **kwargs: Any) -> Any: ...
    async def delete(self, user_id: UUID) -> None: ...


class RedisProtocol(Protocol):
    async def set(self, key: str, value: str, ex: int | None = None) -> None: ...
    async def get(self, key: str) -> str | None: ...
    async def exists(self, key: str) -> bool: ...


class EmailProtocol(Protocol):
    async def send_verification_email(self, email: str, token: str) -> None: ...
    async def send_reset_password_email(self, email: str, token: str) -> None: ...
